### ISSUE TITLE
Import Error: No module named termcolor

### ISSUE THREAD

**Issue by iEscapedVim** [stormshadow07/BeeF-Over-Wan#14]
root@Markhor:~/Desktop/BeeF-Over-Wan# chmod +x BeeFOverWan.py && python BeeFOverWan.py
Traceback (most recent call last):
  File "BeeFOverWan.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor

**Comment by tejan-singh** [comment]
FOUND IT!

sudo apt-get install python-pip
sudo pip install termcolor
