### ISSUE TITLE
No module name termcolor

### ISSUE THREAD

**Issue by swarnava101** [stormshadow07/BeeF-Over-Wan#29]
when im using python BeeFOverWan.py 
then giving error ile "BeeFOverWan.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor

i tried to install by pip3 install termcolor but its saying  
Requirement already satisfied: termcolor in /usr/local/lib/python3.8/dist-packages (1.1.0)
kindly help

**Comment by swarnava101** [comment]
solved
just google and download termcolor tar file
extract it
then run python setup.py install
then try running beef again by python
it will run

**Comment by SiamAhmed00** [comment]
thanks it worked

**Comment by JuanPabloGarciaMonzon** [comment]
run python2.7 BeeFOverWan.py
