### ISSUE TITLE
ERROR:  Your configuration file must define

### ISSUE THREAD

**Issue by karencho777** [stormshadow07/BeeF-Over-Wan#4]
I am getting such error:

ERROR:  Your configuration file must define at least one tunnel when using --all. To intentionally start no tunnels, use `ngrok start --none.`

content of the /root/.ngrok2/ngrok.yml : 
tunnels:
first-app:
addr: 80
proto: http
second-app:
addr: 3000
proto: http
 
What i am doing wrong?

**Comment by karencho777** [comment]
no one can help?

**Comment by stormshadow07** [comment]
Sorry for late reply,  I don't get any email or notification of any issue or comment so...

This is My Config file Setting:

tunnels:
  first-app:
    addr: 80
    proto: http
  second-app:
    addr: 3000
    proto: http

And i think it is same.
Start ngrok using this Command : `ngrok start -all`
 
I hope it helps  , if not kindly mail me.

**Comment by karencho777** [comment]
i do start with this command, but still the same error

**Comment by stormshadow07** [comment]
Send me screenshot .
I have tested now , ngrok has stopped giving multiple tunnels on free
account . So thats why you might getting this error

**Comment by karencho777** [comment]
https://b.radikal.ru/b41/1806/09/516a460a44ee.png

here is screenshot

**Comment by stormshadow07** [comment]
This issue is not regarding the script. I have tried it and it works fine.
This issue is at your end, kindly google for the solutions first if not
resolved i will see

**Comment by karencho777** [comment]
oh i have tried all google stuff that i found, but still, i just dont get it why it is not turning on((( i created everything like in tutorial ... the config file and stuff... but can it be because i did not authinticate myself? in the ngrok?

**Comment by stormshadow07** [comment]
Ohh man. Are you saying you have put auth code inside config file? If thats
it, do it do it.

**Comment by karencho777** [comment]
no, i am saying that i didnot put the auth code in config file, do i need to do it?

**Comment by stormshadow07** [comment]
Yes thats obvious.

**Comment by karencho777** [comment]
sorry that is not for me, i am noob )))

**Comment by stormshadow07** [comment]
Okay np , hope this works for you

On 10-Jun-2018 8:15 pm, "karencho777" <notifications@github.com> wrote:

sorry that is not for me, i am noob )))

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/stormshadow07/BeeF-Over-Wan/issues/4#issuecomment-396054616>,
or mute the thread

**Comment by karencho777** [comment]
i did the authcode in config file but still the same error

**Comment by karencho777** [comment]
i have the config file and there is at least one tunnel why it is giving the same error

**Comment by stormshadow07** [comment]
Try the command - ngrok http 80

See if it works fine

**Comment by karencho777** [comment]
Yes works perfectly

**Comment by stormshadow07** [comment]
Okay that means . Single tunnel is working . Sear h for multiple tunnels
and it fixes

**Comment by karencho777** [comment]
how can i search for multiple tunnels? at the ngrok documentation explained same config file like we did above

**Comment by stormshadow07** [comment]
Man i dont know , becaise its working on my end . Make sure you have
premium account not free becoz even if it worked ngrok now allows only 1
tunnel for free

**Comment by karencho777** [comment]
For quick demos and other simple tunneling needs.

    HTTP/TCP tunnels on random URLs/ports
    1 online ngrok process
    4 tunnels/ngrok process
    40 connections / minute

4 Tunnels per free account

**Comment by stormshadow07** [comment]
I said this because when i tried to run ngrok for this script , i got error
saying you have to buy premium to open multiple tunnels

**Comment by joakinmax** [comment]
i have a problem i have the authtoken in ngrok.yml and i add too
tunnels:
  	first-app:
    	addr: 80
    	proto: http
  	second-app:
    	addr: 3000
    	proto: http
and when i put ngrok start --all is this error look 

ERROR:  Failed to read configuration: Error reading configuration file '/root/.ngrok2/ngrok.yml': Config contains tab characters. YAML must use spaces for indentation.
ERROR:
what can i do plx help me

**Comment by ghost** [comment]
> i have a problem i have the authtoken in ngrok.yml and i add too
> tunnels:
> first-app:
> addr: 80
> proto: http
> second-app:
> addr: 3000
> proto: http
> and when i put ngrok start --all is this error look
> 
> ERROR: Failed to read configuration: Error reading configuration file '/root/.ngrok2/ngrok.yml': Config contains tab characters. YAML must use spaces for indentation.
> ERROR:
> what can i do plx help me

put 4 spaces before first app and second app
and put 8 spaces before addr and proto

**Comment by Raghavklnx** [comment]
Same error can anyone help?

**Comment by jusce17** [comment]
I faced the same just now, it is possible that your system is not recognizing the file locations just yet (I am on linux) tried few mins later and it worked 

make sure you run the command
`ngrok authtoken <YOUR_AUTHTOKEN>`

so it can create the file `ngrok.yml ` and add your auth token to it. After that head to the file and your tunnels 
The location of the file depends on the system you are running on 


```
(Linux) /home/example/.ngrok2/ngrok.yml
(OS X) /Users/example/.ngrok2/ngrok.yml
(Windows) C:\Users\example\.ngrok2\ngrok.yml

```

**Comment by Makveli** [comment]
GOT IT. 
tunnels:
    first-app:
        addr: 80
        proto: http
    second-app:
        addr: 3000
        proto: http

coy paste this then and spaces with space bar only no tabs

tunnels:
first-app: + 4 spaces
addr: 80 + 8 spaces and so on
proto: http
second-app:
addr: 3000
proto: http

**Comment by Cwoar** [comment]
I have two problems I hope someone can help me with. First may not be a problem but for every tutorial I have seen the ngrok tunnel url is a short alpha numerical link. Can anyone explain why the link that is generating for me is formatting like this.

http://4283-81-154-893-233.ngrok.io 

It just doesnt look correct. Secondly when I actually get BoW running I can not authenticate. When entering the username and password i am just redirected back to the authentication page. (there is no invalid username/password error so I know im putting it in correctly)

**Comment by Makveli** [comment]
You need a paid version

**Comment by Makveli** [comment]
You need to access the beef config file and change I think
allow_reverse_proxy: true

**Comment by Makveli** [comment]
Happy Hunting

**Comment by Makveli** [comment]
/etc/beef-xss/config.yaml

**Comment by Makveli** [comment]
It is only $10 a month for paid version. Well worth it

**Comment by Makveli** [comment]
Have a good day

**Comment by Cwoar** [comment]
Thank you all for you ridiculously fast responses I will sort this all now. Thanks a lot!

**Comment by Makveli** [comment]
You're welcome!

**Comment by khu-twilio** [comment]
> > i have a problem i have the authtoken in ngrok.yml and i add too
> > tunnels:
> > first-app:
> > addr: 80
> > proto: http
> > second-app:
> > addr: 3000
> > proto: http
> > and when i put ngrok start --all is this error look
> > ERROR: Failed to read configuration: Error reading configuration file '/root/.ngrok2/ngrok.yml': Config contains tab characters. YAML must use spaces for indentation.
> > ERROR:
> > what can i do plx help me
> 
> put 4 spaces before first app and second app and put 8 spaces before addr and proto

This helped me perfectly

**Comment by Makveli** [comment]
Then You can login

**Comment by Aarav5255** [comment]
wait so do you need a paid version of ngrok or not

**Comment by petini96** [comment]
Hi friend, for me, nothing this works...

I'm using WSL(Ubuntu) and windows docker desktop. Only thing that works for me:

**docker-compose.yml**

```
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 0.0.0.0:4040:4040

```

**ngrok.yml**
 
```
version: 2
authtoken: 29aFgTqRqRQbrdpGzJSEdvbzsBx_7kr7dCFtAAGs7Z7nqwSQi
region: sa
dns_resolver_ips:
  - 1.1.1.1
  - 8.8.8.8
crl_noverify: true
web_allow_hosts:
  - 127.0.0.1
tunnels:
  typebotbuilder:
    proto: http
    addr: http://host.docker.internal:3001
  typebotviewer:
    proto: http
    addr: http://host.docker.internal:3002
  portaevolution:
    proto: http
    addr: http://host.docker.internal:8080
  
```

This way... I can enter on http://127.0.0.1:4040/status then access my tunnels link, like:
   
![image](https://github.com/user-attachments/assets/055b181b-ffca-434b-9852-352b353f395b)

works fine! I read the docs:
https://ngrok.com/docs/agent/config/v2/
https://ngrok.com/docs/using-ngrok-with/docker/

**Comment by Alhuzsyam** [comment]
its work for me
version: "2"
authtoken: *put your key here*
tunnels:
    web:
        proto: http
        addr: 80
        inspect: false
    tcp1:
        proto: tcp
        addr: 3306
    tcp2:
        proto: tcp
        addr: 4000

and start with this command 
ngrok start --all --config ./ngrok.yml

**Comment by Aiziyou918** [comment]
Config file ngrok.yml:

version: "2"
authtoken: *put your key here*

tunnels:
    first-app:
        proto: http
        addr: 80
    second-app:
        proto: http
        addr: 3000
Works if you start with:

ngrok start --all --config ./ngrok.yml
