### ISSUE TITLE
The error encountered was: dial tcp [::1]:3000: getsockopt: connection refused

### ISSUE THREAD

**Issue by dcliss** [stormshadow07/BeeF-Over-Wan#5]
hi there , i have a premium version of ngrok and everything worked as your said except for the beefadmin url Any help

i get this when i open the link . posted some screenshots so it will be easy for you .

Failed to complete tunnel connection

The connection to http://edfd1550.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:3000.

Make sure that a web service is running on localhost:3000 and that it is a valid address.

The error encountered was: dial tcp [::1]:3000: getsockopt: connection refused
![screen shot 2018-09-26 at 2 40 29 pm](https://user-images.githubusercontent.com/32026802/46069912-41ed5f80-c19a-11e8-9532-5ea87ded2b3b.png)
![screen shot 2018-09-26 at 2 41 45 pm](https://user-images.githubusercontent.com/32026802/46069951-55002f80-c19a-11e8-92b7-50e1e79ffaf3.png)
![screen shot 2018-09-26 at 2 40 29 pm](https://user-images.githubusercontent.com/32026802/46069987-634e4b80-c19a-11e8-8b88-2fb4bd809f6a.png)
![screen shot 2018-09-26 at 2 40 34 pm](https://user-images.githubusercontent.com/32026802/46069988-634e4b80-c19a-11e8-94a5-34423726bbf8.png)
![screen shot 2018-09-26 at 2 40 55 pm](https://user-images.githubusercontent.com/32026802/46069989-63e6e200-c19a-11e8-9f0a-4b8f4ecb8a61.png)
![screen shot 2018-09-26 at 2 41 45 pm](https://user-images.githubusercontent.com/32026802/46069990-63e6e200-c19a-11e8-983f-802dd0e8d935.png)

**Comment by dcliss** [comment]
Kindly close this some service was used by local host . worked flawlessy !! Great tool !! Cheers mate

**Comment by pretech86** [comment]
excuse me can you explain how to solve this error

**Comment by jesse234** [comment]
waste of time bro this tools can not work after kali update , try using beef and portforward in your router
